// import './@decentraland/CommunicationsController'
// import './@decentraland/EnvironmentAPI'
// import './@decentraland/EthereumController'
// import './@decentraland/SocialController'
// import './@decentraland/ParcelIdentity'
// import './@decentraland/web3-provider'
// import './@decentraland/Identity'
// import './@decentraland/SignedFetch'
// import './@decentraland/Players'
// import './@decentraland/RestrictedActions'
// import './@decentraland/PortableExperiences'
import './cube-scene'
